### ISSUE TITLE
Multiple group

### ISSUE THREAD

**Issue by AYMENJD** [callsmusic/tgvc-userbot#3]
Hi can u add support to multiple group calls means the bot works on 2+ calls on Different groups

**Comment by vvr3ddy** [comment]
I guess that isnt possible because tg-calls api doesnt support calls on multiple groups at once.

**Comment by AYMENJD** [comment]
Hmm , i have one of my userbot working on two calls with different session

**Comment by dashezup** [comment]
It's possible.

Actually it worked for multiple groups previously, but I dropped multiple voice chats support when I add playlist feature 11 days ago, check https://github.com/callsmusic/tgvc-userbot/commit/19405d17aa203e02c438cfcaf11ba63d33b7844e, but it plays the same audio across different voice chats.

Reasons I dropped multiple voice chats support:
1. **Code simplicity**. After add playlist feature, the code could be messy when it needs to have each playlist for each group.
2. **Resource consumption**. For each voice chat requires each `GroupCall` instance, and having multiple GroupCall instance may cause huge CPU usage. in my case, 35% CPU usage for 1 `GroupCall` instance, and 55% CPU usage for 2 `GroupCall` instance. 80% or 100% CPU usage for 3 or 4 GroupCall instance and the played audio starts lagging. The server is quite low end btw. For People who run it on Heroku with free dyno, it already lags for one single voice chat, and I've heard some people complains that it even lags sometimes with premium ones.
3. **Disk consumption**. The userbot download audio from Telegram, and then use `ffmpeg` to convert it to RAW PCM and then pytgcalls could use it. Here is the filesize of raw PCM regarding other factors. It's a bit slow to transcode audio files to RAW PCM, and those consume lots of disk space. Imagine some people add some live sets in multiple voice chats, `ffmpeg` can't be run as real async. This may block some process and make the bot delay to response. I don't have much disk space to use.
```
filesize_in_bytes / second == channel * sample_rate * bit_depth / 8

| duration | filesize |
|----------|----------|
|       1M |   10.98M |
|       4M |   43.94M |
|      10M |  109.86M |
|       1H |  659.17M |
|       2H |    1.28G |
|       4H |    2.57G |
```
4. **Not that much people need multiple voice chats support** a few of people asked about multiple voice chats support, but I don't think there are that much. It does not worth the above effect to have this feature, could potentially cause issues and most of people don't use it.

And I'm rewriting the project, it will probably have channel voice chat support in the further, channel VC support along with multiple voice chats could make it more messy.

Discussion is welcome, we could talk about this.

**Comment by AYMENJD** [comment]
Hmm all ur reasons are convincing .

1) Try to make the code less messy as u can;
2) Hmm, for me i on Ubuntu 18 LTS (1ram 1cpu) its use 10% of 1 `GroupCall` 
3) Yes, it can be solved by limit :
How many group call can work .
File size .
Audio Duration .
ex in main.py
```
GROUP_CALL_COUNT = 4 # It will allow 4 GroupCall instance in this session

FILESIZE = 50000000 # 50mb in bytes as limit for the audio file will be downloaded from telegram

DURATION = 3600 # 1h in seconds as limit for the audio file duration
```
4) in my cause of arab people they love it and ask me to make it for multiple groups i don't know much about python i use MadelineProtoPHP but till now their is no support for group calls

My idea is to make it but less messy by using ur coding magic also to make the user choose .
 
Cpu and disk is not my problem i can run it on big server also by make the user limit what he wants make it can run on small server and big server

**Comment by dashezup** [comment]
btw yeah multiple sessions should work for now. (each session for each group, by using custom `userbot.py` or something)

regarding duration limitation, for now the dev branch one does not set any duration limitation. the `autoplay` branch automatically take new audio which duration less than 10min in group into playlist and seems people like it. The rewrite will have this feature as well.

The main purpose of rewriting the project is that making it easier to use. avoid using commands etc.

Maybe we'll keep this issue open for a while, it could be the thing I may consider after the rewrite.

**Comment by Olgabrezel** [comment]
Well, we implemented it. See you :​)

**Comment by dashezup** [comment]
I decided to not rewrite it because it break the simplicity of the current behaviors/codes.

For someone who need the userbot work for multiple groups, just use multiple sessions, it seems to just works.

**Comment by AYMENJD** [comment]
I just store GroupCall instance in a var[chat_id] dict and i call it by group chat id

**Comment by dashezup** [comment]
> I just store GroupCall instance in a var[chat_id] dict and i call it by group chat id

How did you deal with playlists? it plays different songs and uses different playlists for different groups, right?

**Comment by AYMENJD** [comment]
> > I just store GroupCall instance in a var[chat_id] dict and i call it by group chat id
> 
> How did you deal with playlists? it plays different songs and uses different playlists for different groups, right?

Exactly, the same way when i store the GroupCall instance if i want to do everything i call it by chat_id of the group to manage playlist[chat_id] etc
