### ISSUE TITLE
Mutiple groups and userbot accounts are controlled by a bot.

### ISSUE THREAD

**Issue by ChankitSaini** [callsmusic/tgvc-userbot#5]
Add feature like @GroupMusicBot which can add userbots of our own into groups for multiple group support. add repeat turn off feature also

**Comment by dashezup** [comment]
Never tried GroupsMusicBot, idk what it's like.

It's already planned to add those features in my wip rewrite of the project.

**Comment by ChankitSaini** [comment]
Okay. Sir
