### ISSUE TITLE
Sound lag

### ISSUE THREAD

**Issue by mlAbolfazl** [callsmusic/tgvc-userbot#7]
The sound is so lagy, can you decrease quality or something to decrease the lag and tearing?
thank you

**Comment by dashezup** [comment]
Switched from heroku docker container to ffmpeg buildpack, it should be less lag on heroku free dyno now.

It's a known issue that it lags on Heroku free dyno, tgcalls requires some CPU resources and Heroku provide very limited CPU resource to free dyno.

There are not much things we can do.

It does not lag on low-end VPS or cloud servers.

**Comment by mlAbolfazl** [comment]
I'm not using heroku, i just use a socks5 proxy which has good internet speed.
I tried vpn too but it's still the same
my server is in a country which telegram is restricted there and i don't have any idea why the sound is laggy
I thought it's because of my network and reduce the quality may fix it.
Anyway thanks for your answer

**Comment by dashezup** [comment]
it could be because of your proxy/VPN.

for proxy, Pyrogram has build-in support for proxy. You can also use something like `proxychains`. try to figure it out by yourself.
