### ISSUE TITLE
not playing

### ISSUE THREAD

**Issue by gautam-kumar71** [callsmusic/tgvc-userbot#8]
whenever i click the voice chat the bot leaves the grp ... don't know why

**Comment by dashezup** [comment]
You can't use one account with two sessions to enter the same voice chat to play and listen at the same time. You are supposed to deploy tgvc-userbot with your alt account and listen to the music with your main account.

**Comment by gautam-kumar71** [comment]
plz give the detailed explanation..Im not able to deploy

**Comment by dashezup** [comment]
README has enough info. you can also join t.me/vcsets to check `/notes` or ask for help.
