### ISSUE TITLE
!leave and !join 

### ISSUE THREAD

**Issue by ghost** [callsmusic/tgvc-userbot#9]
!leave and !join  are Not Stable...

Sounds Lags

**Comment by dashezup** [comment]
MarsharX/tgcalls used to have issue that it can't be fully stopped, but it should be fine now (fixed some weeks ago), recent deployment shouldn't have this issue.

Lags only on Heroku, it's not problem of this project but Heroku provide very limited CPU resource.

Stop being boring by saying something like this over and over again. If you want to report a bug then provide step to reproduce and logs.
